### PR TITLE
Create opportunity functionality added

### PR DESCRIPTION
**Pull request by simonsayz13**
1. Updated create opportunity model forms:
- Add locations selector
- Add number of slot input field

2. Submitting create opportunity form adds the data onto RTDB

### CODE REVIEW

**Comment by R-Middleton** [comment]
All looks good but due to the (admittedly not great) code duplication between opportunity.js & opportunityLg.js, the form wont work on the mobile navbar that uses the former. I think you should probably just copy paste all the useState() and other stuff from opportunityLg and add it to the mobile opportunity.js. Hopefully this makes sense!

**Review by R-Middleton — CHANGES_REQUESTED** [review]
Copied from the main conversation -
All looks good but due to the (admittedly not great) code duplication between opportunity.js & opportunityLg.js, the form wont work on the mobile navbar that uses the former. I think you should probably just copy paste all the useState() and other stuff from opportunityLg and add it to the mobile opportunity.js. Hopefully this makes sense!

**Comment by simonsayz13** [comment]
> All looks good but due to the (admittedly not great) code duplication between opportunity.js & opportunityLg.js, the form wont work on the mobile navbar that uses the former. I think you should probably just copy paste all the useState() and other stuff from opportunityLg and add it to the mobile opportunity.js. Hopefully this makes sense!

**Review by R-Middleton — APPROVED** [review]
Well done :party-wizard:

**Pull request merged**
